version: '3.8'

services:
  frontend:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    image: yusup26/django-todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
    restart: always
    env_file:
      - ./../deploy/.env
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"

  migrations:
    image: yusup26/django-todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./../deploy/.env
    command:
      sh -c "python ./manage.py migrate"

  db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - ./../deploy/.env
    volumes:
      - todolist:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      timeout: 15s
      interval: 4s
      retries: 10


volumes:
  todolist: