# Generated by Django 4.2.1 on 2023-07-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(max_length=12, verbose_name='Код подтверждения'),
        ),
    ]
