name: Build and deploy action
on:
  push:
    branches: ["master"]


jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and Push Container
        run: |-
          docker build -t yusup26/django-todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
          docker push yusup26/django-todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    needs: build_and_push
    runs-on: ubuntu-20.04
    env:

      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DEBUG: ${{secrets.DEBUG}}

    steps:
      - name: Clone Code
        uses: actions/checkout@v3.5.2